### ISSUE TITLE
Job for jboss.service failed because a configured resource limit was exceeded

### ISSUE THREAD

**Issue by venerari** [ansible/ansible-examples#227]
Job for jboss.service failed because a configured resource limit was exceeded

I'm using centos7.  How can I fixed this?

See also the logs,

[root@centos1 jboss-standalone]# journalctl -xe
May 09 19:28:50 centos1 jboss[5825]: at org.jboss.modules.Main.main(Main.java:255)
May 09 19:28:50 centos1 jboss[5825]: Caused by: java.lang.NullPointerException
May 09 19:28:50 centos1 jboss[5825]: at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:94)
May 09 19:28:50 centos1 jboss[5825]: at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:87)
May 09 19:28:50 centos1 jboss[5825]: at __redirected.__SAXParserFactory.<init>(__SAXParserFactory.java:102)
May 09 19:28:50 centos1 jboss[5825]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
May 09 19:28:50 centos1 jboss[5825]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.j
May 09 19:28:50 centos1 jboss[5825]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccess
May 09 19:28:50 centos1 jboss[5825]: at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
May 09 19:28:50 centos1 jboss[5825]: at java.lang.Class.newInstance(Class.java:383)
May 09 19:28:50 centos1 jboss[5825]: at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:179)
May 09 19:28:50 centos1 jboss[5825]: at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:147)
May 09 19:28:50 centos1 jboss[5825]: at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:219)
May 09 19:28:50 centos1 jboss[5825]: at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:126)
May 09 19:28:50 centos1 jboss[5825]: ... 19 more
May 09 19:28:50 centos1 su[5835]: pam_unix(su-l:session): session closed for user jboss

Thanks.

**Comment by rcarrata** [comment]
Hi @venerari, 

I hit the same error and I found the solution:

https://stackoverflow.com/questions/48403832/javax-xml-parsers-factoryconfigurationerror-running-jboss-as-7-1-with-java-7-upd

```
[root@ip- jboss-as]# wget -O jboss-modules.jar http://repo1.maven.org/maven2/org/jboss/modules/jboss-modules/1.1.5.GA/jboss-modules-1.1.5.GA.jar                                                                                                                            

[root@ip- jboss-as]# chmod jboss:jboss jboss-modules.jar
[root@ip- jboss-as]# /etc/init.d/jboss start
```

I'll make a PR into the repo for try to solve this.

Cheers!

R.
