### ISSUE TITLE
hadoop playbook  file permission

### ISSUE THREAD

**Issue by kevinbin** [ansible/ansible-examples#58]
[root@GroupI-LTMP-1 ~]# ll /etc/hadoop/conf/
总用量 60
-rw-r--r-- 1 root root 1335 11月 21 07:25 configuration.xsl
-rw-r--r-- 1 root root 1009 2月  25 17:06 core-site.xml
-rw-r--r-- 1 root root 1773 2月  25 17:06 hadoop-metrics2.properties
-rw-r--r-- 1 root root 2489 2月  25 17:06 hadoop-metrics.properties
-rw-r--r-- 1 root root 9196 11月 21 07:25 hadoop-policy.xml
-rw-r--r-- 1 root root 1791 2月  25 17:06 hdfs-site.xml
-rw-r--r-- 1 root root 8735 11月 21 07:25 log4j.properties
-rw------- 1 root root  461 2月  25 17:06 mapred-site.xml

14/02/25 17:21:12 FATAL conf.Configuration: error parsing conf mapred-site.xml
java.io.FileNotFoundException: /etc/hadoop/conf.empty/mapred-site.xml (Permission denied)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at java.io.FileInputStream.<init>(FileInputStream.java:79)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:70)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:161)
	at java.net.URL.openStream(URL.java:1010)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2030)

why only mapred-site.xml is 600?

**Comment by bcoca** [comment]
I think this issue is on the wrong repo as there is nothing hadoop related here
